### ISSUE TITLE
Run promise programmatically

### ISSUE THREAD

**Issue by luciorubeens** [posva/vue-promised#11]
Instead of executing the promise when it was set, add the ability to execute when we want. Perhaps adding an optional prop and a method.

Something like:

```
<promised ref="promised" :promise="promise" :immediate="false" />

this.$refs.promised.run()
```

This will facilitate use cases when a component has one asynchronous method that can be called multiple times.

**Comment by posva** [comment]
It's actually pretty much the same thing except that you cannot _"call"_ a promise multiple time but by assigning it becomes natural because it is always a new one
The way to go is to set the `promise` to a new Promise when you need to call the asynchronous method. Instead of writing `this.$refs.promised.run()` you do `this.promise = fetachSomething()`. You can even use a computed property so the fetch call is done automatically if it depends on data.

I think I need to add more docs about patterns that make the code easy to write. I have now used it in many ways and I should share some of my experiences about it :)
