### ISSUE TITLE
Type check failed for prop "promise". Expected Promise, got Promise.

### ISSUE THREAD

**Issue by hadyanq** [posva/vue-promised#9]
Hello, thank you very much for the very useful project.
The component works as expected, however I keep getting strange error on the console.

`[Vue warn]: Invalid prop: type check failed for prop "promise". Expected Promise, got Promise.`

I have no idea how this can become a problem since it's exactly what the component expects, right?
I am using Nuxt, if that matters, and here's the code of my view:
```
<Promised :promise="checkImage(resto.pic)">
  <div slot="pending">Loading...</div>
  <v-card-media slot="then" slot-scope="data" :src="data" height="150px"/>        
  <v-card-media slot="catch" slot-scope="error" :src="error" height="150px"/>
</Promised>
```
Here's the method which returns the promise:
```
checkImage(src) {
  return new Promise((resolve, reject) => {		
    let img = new Image()
    img.src = src

    img.onload = () => resolve(src)
    img.onerror = () => reject("/images/resto-placeholder.png")
  })
}
```
Is there anything wrong on my end? Any help and feedback is greatly appreciated.
Thank you.

**Comment by posva** [comment]
This is because you are using a polyfill for Promises and it's being included after VuePromised is included, making the type differ. The solution is making sure the polyfill is included before VuePromised. It had bit me before, so I will probably just use a custom validator that checks for `then` and `catch` methods

**Comment by hadyanq** [comment]
Thank you for pointing that out. I... am still clueless about polyfill and I'm going to get some reading first and I'll get back if I have something specific to ask. Thanks again :)

**Comment by bodograumann** [comment]
@posva, I‘m having the same problem in a wrapper component for `<Promised>`. Is there an easy way to control the import order of the polyfill in a `vue-cli` application? Otherwise I will have to remove the type checks for `Promise`.

**Comment by posva** [comment]
This was fixed so what error are you seeing?

**Comment by bodograumann** [comment]
@posva, sorry if this might be a little off-topic. I’m using the `promise: { type: Promise }` specification for a prop in my wrapper component and this leads to the same error as reported above.

You solved this by changing the prop definition, but said it was actually caused by the Promise polyfill being imported only after `vue-promised`. So I was wondering if you had a solution in mind, where one would control the import order of the polyfill.

**Comment by posva** [comment]
oh, I'm sorry I don't have a different solution in mind apart from the one I implemented in vue-promised
