### ISSUE TITLE
`isPending` is `true` by default

### ISSUE THREAD

**Issue by rigwild** [posva/vue-promised#95]
Hey,

I started to use the `combined` slot as I find it more flexible for forms disabled states.

For example:
```vue
<Promised :promise="promise" v-slot:combined="{ isPending, data, error }">
  <button @click="refreshValue" :disabled="isPending">
    Load
  </button>

  <Loader v-if="isPending" />
  <textarea v-else-if="data" v-text="data"></textarea>
  <Alert v-else-if="error" v-text="error" />
</Promised>
```

By default, `isPending` is initialized as `true` when promise is initialized as `null`. This is frustrating as it makes the form being rendered as in a loading state (at first I was confused as it is not what I expected, and could not find the problem).

https://github.com/posva/vue-promised/blob/fe001cf79f41cdccfde31cc711309143d447ad7b/src/index.js#L20-L26
https://github.com/posva/vue-promised/blob/fe001cf79f41cdccfde31cc711309143d447ad7b/src/index.js#L29-L35

The workAround I use is to set a resolved Promise as initialization, but I don't think that is very beautiful 👀 
```vue
data() {
  return {
    promise: Promise.resolve()
  }
}
```

Maybe a prop could be added to init as `false` instead of `true`.

That's not a huge deal though.

Have a nice day!

**Comment by posva** [comment]
This is intentional so the promise is on a pending state until there is something to wait for. Using a resolved promise to make the state automatically go into resolved is the way to go. It clearly expresses that we start as resolved
Promised is meant to reflect the 3 states of a promise, introducing new ones only complexifies the api and detach it more from the js promises

**Comment by rigwild** [comment]
I get your point. This issue may be useful to others who are facing the same problem!
Have a nice day :smile_cat:
